### ISSUE TITLE
Date picker should use local time zone

### ISSUE THREAD

**Issue by jdzak** [NUARIG/nu_surveyor#48]
Currently the date picker is not setting a timezone, so it's defaulting to +0000. If expecting to save the date 2011-12-13 00:00:00 -6000, instead the date that will be saved is 2011-12-13 06:00:00 +0000.

**Comment by rsutphin** [comment]
Those are the same date, though. This sounds like a display problem rather than a save problem.

**Comment by jdzak** [comment]
So this functionality is fine, the date/time is the same.
