### ISSUE TITLE
Quartz linker errors

### ISSUE THREAD

**Issue by jdzak** [NUARIG/nu_surveyor#55]
I receive the following linker errors when trying to run surveyor within my project. It looks like I'm missing the QuartzCore framework.

<pre>
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CAShapeLayer", referenced from:
      objc-class-ref in libNUSurveyor.a(NUAnyCell.o)
      objc-class-ref in libNUSurveyor.a(NUOneCell.o)
  "_kCALineCapRound", referenced from:
      -[NUAnyCell initWithStyle:reuseIdentifier:] in libNUSurveyor.a(NUAnyCell.o)
  "_OBJC_CLASS_$_CAGradientLayer", referenced from:
      objc-class-ref in libNUSurveyor.a(NUButton.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

**Comment by yoon** [comment]
NUSurveyor now has QuartzCore.framework in "Build Phases" -> "Link Binary With Libraries". Is this still an issue?

**Comment by jdzak** [comment]
I think this is fixed.  I didn't run into this last time I upgraded.
