### ISSUE TITLE
Lines of text aren't wrapping properly

### ISSUE THREAD

**Issue by jdzak** [NUARIG/nu_surveyor#59]
If an instrument has new line characters in the question/label text, the survey will wrap.  This functionality is different than surveyor web where the browser interprets newlines as white space.

We should interpret like breaks as white space.

**Comment by yoon** [comment]
In that case, there's will be absolutely no way to have line breaks in labels, which was requested functionality.

**Comment by jdzak** [comment]
That should be fine.  If a newline is needed, we could just break a label into two.

**Comment by rsutphin** [comment]
I agree with @jdzak. Labels should be rendered in iOS the same way they'd be rendered in the web version, meaning with normalized whitespace.

**Comment by rsutphin** [comment]
In addition to questions and labels, this issue also applies to help text.
