### ISSUE TITLE
Add 'Done' button to end of survey

### ISSUE THREAD

**Issue by jdzak** [NUARIG/nu_surveyor#62]
At the end of the survey, the user should be presented with a "Done" button.

**Comment by yoon** [comment]
In surveyor web, there's a default place to go when the "Done" button is pressed. Where should it go with surveyor iOS?

**Comment by jdzak** [comment]
Good question.

Personally, I'd like to know when the survey is done so i could pop the
survey controller from the navigation controller and then swap the section
controller with my controller.  Would it make sense to have some sort of
delegate handle this or a NSNotification that the survey is complete?

On Thu, Feb 16, 2012 at 2:41 PM, yoon <
reply@reply.github.com
