### ISSUE TITLE
Mustache renders blank when mustache variable doesn't exist in context.

### ISSUE THREAD

**Issue by yoon** [NUARIG/nu_surveyor#89]
@jdzak can you add some notes about possible solutions?

**Comment by jdzak** [comment]
I think we should leave the variable when there's nothing to substitute from the context. I feel this is less confusing than substituting blank, for the person reading the survey. Also, I think by leaving these variables, they could be used as text ques so the person reading the survey could substitute in their own text.

**Comment by rsutphin** [comment]
I agree with @jdzak. It also makes it clearer to a person scanning-but-not-reading the rendered survey that there's something missing.
