### ISSUE TITLE
Moving from text field to text field without hiding keyboard won't save responses

### ISSUE THREAD

**Issue by jdzak** [NUARIG/nu_surveyor#93]
When a user moves from one text field to a second without hiding the keyboard in between, the first text field will not save the response entered.

**Comment by yoon** [comment]
I'm unable to reproduce this error right now, any examples?

**Comment by yoon** [comment]
In the kitchen sink, fill in "who" with "me", then scroll it off the page. Hide the keyboard, then scroll back.
